# Generated by Django 4.2.2 on 2023-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_taskcoin_taskchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='has_access',
            field=models.BooleanField(default=True),
        ),
    ]
