# Generated by Django 4.2.2 on 2023-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_taskuser_has_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskchecklist',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
