# Generated by Django 4.2.2 on 2024-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open_time', models.PositiveBigIntegerField(null=True)),
                ('open_price', models.CharField(max_length=50, null=True)),
                ('high_price', models.CharField(max_length=50, null=True)),
                ('low_price', models.CharField(max_length=50, null=True)),
                ('close_price', models.CharField(max_length=50, null=True)),
                ('volume', models.CharField(max_length=50, null=True)),
                ('close_time', models.PositiveBigIntegerField(null=True)),
                ('quote_asset_volume', models.CharField(max_length=50, null=True)),
                ('number_of_trades', models.PositiveBigIntegerField(null=True)),
                ('taker_by_base_asset_volume', models.CharField(max_length=50, null=True)),
                ('taker_by_quote_asset_volume', models.CharField(max_length=50, null=True)),
                ('engulfing_bullish', models.BooleanField(default=None, null=True)),
                ('engulfing_bearish', models.BooleanField(default=None, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
