# Generated by Django 4.2.2 on 2024-01-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_exchangetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransaction',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='exchange_app.exchange'),
        ),
    ]
