# Generated by Django 4.2.2 on 2024-02-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_timeframe_exchangetransaction_time_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangetransaction',
            name='exchange',
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='exchange_app.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='exchange_app.symbol'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('exchange', 'name'), name='Unique symbol for each exchange.'),
        ),
    ]
