# Generated by Django 4.2.2 on 2024-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0005_remove_exchangetransaction_exchange_symbol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangetransaction',
            options={},
        ),
        migrations.AddConstraint(
            model_name='exchangetransaction',
            constraint=models.UniqueConstraint(fields=('symbol', 'open_time'), name='Unique transaction for each symbol.'),
        ),
    ]
