# Generated by Django 4.2.2 on 2024-02-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0006_alter_exchangetransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframe',
            name='time',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
