# Generated by Django 4.2.2 on 2024-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0007_alter_timeframe_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeframe',
            old_name='time',
            new_name='name',
        ),
    ]
