# Generated by Django 4.2.2 on 2024-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0008_rename_time_timeframe_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangetransaction',
            name='Unique transaction for each symbol.',
        ),
        migrations.AddConstraint(
            model_name='exchangetransaction',
            constraint=models.UniqueConstraint(fields=('symbol', 'open_time', 'time_frame'), name='Unique transaction for each symbol.'),
        ),
    ]
