# Generated by Django 4.2.2 on 2024-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0009_remove_exchangetransaction_unique_transaction_for_each_symbol__and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='seconds',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
