# Generated by Django 4.2.2 on 2024-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0010_timeframe_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeframe',
            options={'ordering': ('seconds',)},
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='engulf_at',
            field=models.DateTimeField(null=True),
        ),
    ]
