# Generated by Django 4.2.2 on 2024-03-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0011_alter_timeframe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_frames', to='exchange_app.exchange'),
        ),
    ]
