# Generated by Django 4.2.2 on 2024-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0012_timeframe_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframe',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='timeframe',
            constraint=models.UniqueConstraint(fields=('exchange', 'name'), name='Unique frame for each exchange.'),
        ),
    ]
