# Generated by Django 4.2.2 on 2023-06-14 03:25

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('badge', model_utils.fields.StatusField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('I', 'Info')], default=None, max_length=100, no_check_for_status=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_authentication', models.BooleanField(default=False)),
                ('is_authorization', models.BooleanField(default=False)),
                ('is_accounting', models.BooleanField(default=False)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('track', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='activity_logger.log')),
            ],
        ),
    ]
